// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dsadas: typeof import("./src/components/icons/dsadas.vue")["default"]
    IcBaselineImage: typeof import('./src/components/icons/IcBaselineImage.vue')['default']
    IcBaselineVolumeUp: typeof import('./src/components/icons/IcBaselineVolumeUp.vue')['default']
    IcOutlineCompareArrows: typeof import('./src/components/icons/IcOutlineCompareArrows.vue')['default']
    IcTwotoneCopyAll: typeof import('./src/components/icons/IcTwotoneCopyAll.vue')['default']
    Images: typeof import('./src/components/icons/images.vue')['default']
    Sdaad: typeof import('./src/components/icons/sdaad.vue')['default']
    VarAppBar: typeof import("@varlet/ui")["_AppBarComponent"]
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
  }
}
